version: '3'

services:
  web:
    build: .
    ports:
      - "80:80"
    environment:
      MYSQL_HOST: database-sportify.cjyqay84wvgi.us-east-1.rds.amazonaws.com
      MYSQL_USER: admin
      MYSQL_PASSWORD: sportify123
      MYSQL_DATABASE: sportifydb
    depends_on:
      - web
